# Generated by Django 5.1.2 on 2024-11-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_guestbook_passward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='passward',
            new_name='password',
        ),
    ]
